packages:
  - "apps/*"
  - "packages/*"
  - "!**/test/**"
  - "!**/fixtures/**"
  - "!**/temp/**"
  - "!packages/tests/temp/**"
allowBuilds:
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
